name: Tourism Wellness MLOps Pipeline

on:
  push:
    branches: [ "main" ]  # Triggers automation whenever you push to main

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Code Quality Check (Linting)
        run: |
          # This check ensures your Python code has no syntax errors before deploying
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # This pushes your GitHub code directly to the Hugging Face hosting server
          git remote add hf https://pvinayv:$HF_TOKEN@huggingface.co/spaces/pvinayv/tourism-wellness-app
          git push --force hf main
